### ISSUE TITLE
ignoredjobs are not working

### ISSUE THREAD

**Issue by underdogminecraft** [tom-osborne/qb-speedcameras#10]
ignoredjobs are not working

**Comment by tom-osborne** [comment]
Can you elaborate please?

- What have you set as ignored jobs? Please share a snippet showing your config.
- What are you expecting to happen?
- What is actually happening?
- Are there any errors in the F8 client console?

Thanks

**Comment by underdogminecraft** [comment]
yes ignored jobs are police and ambulance
but its not ignoring these jobs
police officers and ems are getting fined as well
![Screenshot 2023-03-28 233355](https://user-images.githubusercontent.com/78051660/228328406-1b6b4a1a-e70d-498b-a7bc-7522953e61bc.png)

no errors in f8 console

**Comment by tom-osborne** [comment]
Thanks for the info.

Is this happening while the police/ambulance are on duty? Could you check that for me?

**Comment by underdogminecraft** [comment]
both on duty and off duty

**Comment by tom-osborne** [comment]
> both on duty and off duty

Okay, so I just tested on my test server and it seems to work as intended. Would you be willing to go into a Discord VC to troubleshoot further?

**Comment by underdogminecraft** [comment]
not possible right now 
that means something is not going through

**Comment by underdogminecraft** [comment]
i have to use job names not job labels right because job name is police and its label se Law Enforcement

**Comment by tom-osborne** [comment]
Yes or there is a specific set of circumstances happening that the script is not accounting for.

Do you have anything modified with regards to your jobs? Perhaps a multi department policejob or something?

**Comment by tom-osborne** [comment]
> i have to use job names not job labels right because job name is police and its label se Law Enforcement

Yes, it is checking your job name. You can see the line of code here:
https://github.com/tom-osborne/qb-speedcameras/blob/main/client/main.lua#L45

```lua
if playerJob.name == job and playerJob.onduty then return true end
```

**Comment by tom-osborne** [comment]
@underdogminecraft did you get this resolved?

**Comment by underdogminecraft** [comment]
thanks for asking but unfortunately not

**Comment by tom-osborne** [comment]
Not enough information provided to resolve this issue.

@underdogminecraft please contact me on Discord if you require further support for this issue. Stan#1969
