### ISSUE TITLE
g-billing

### ISSUE THREAD

**Issue by bl0ody41** [tom-osborne/qb-speedcameras#13]
hi my friend how can be use this with g-billing script?

**Comment by tom-osborne** [comment]
@bl0ody41 You can edit this server side event to trigger any relevent exports from g-billing:

https://github.com/tom-osborne/qb-speedcameras/blob/main/client/main.lua#L73

**Comment by bl0ody41** [comment]
i dont undersand am i add this triggerserverevent in g-billing?

**Comment by tom-osborne** [comment]
@bl0ody41 No, you can replace the line of code that I linked with the appropriate export or event.

**Comment by bl0ody41** [comment]
TriggerServerEvent('g-billing:server:getPaidBills') this event?  @tom-osborne

**Comment by tom-osborne** [comment]
@bl0ody41 No idea, never used g-billing. Check their documentation or ask the developer.
