### ISSUE TITLE
[Suggestion] GKS Phone Integration

### ISSUE THREAD

**Issue by ckaysone380** [tom-osborne/qb-speedcameras#4]
If it possible to add support for gkn phone? to allow speedcameras to send bills to the players and the funds that are paid go to a city hall or police society fund?

**Comment by tom-osborne** [comment]
I can look into it.

@ckaysone380 is GKN phone open source?

**Comment by tom-osborne** [comment]
Do you mean GKS phone?
This: https://fivem.gkshop.org/package/4862478

**Comment by tom-osborne** [comment]
@ckaysone380 
If you are using https://fivem.gkshop.org/package/4862478 (QBCore), you will need to edit the follow lines and replace with this.

Search `TriggerServerEvent('qb-phone:server:sendNewMail', {`

Replace with `TriggerServerEvent('gksphone:NewMail', {`

Also you will need to remove the `qb-phone` Dependencie from the `fxmanifest.lua`
