### ISSUE TITLE
[Suggestion] Option to only bill if vehicle is owned by player

### ISSUE THREAD

**Issue by jaylac2000** [tom-osborne/qb-speedcameras#5]
add support to only fine players if its a player owned vehicle and its the owner driving

cd_dispatch offers this option

**Comment by tom-osborne** [comment]
Great suggestion. I have added this feature in https://github.com/tom-osborne/qb-speedcameras/commit/4838b42feb74af39b313d8a85c99db112db04ad3

Please update to use this feature.

**Comment by jaylac2000** [comment]
thank you so much!!
